import type { PublicCopy } from './zh';

const MONTHS = ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

/** Investor-facing English for the public marketing site. */
export const en: PublicCopy = {
  metaDescription: 'GO Marketing Center is the AI marketing system behind TaskGo, Homigo, and Washgo. AI editors draft in each brand voice, people review, then posts go out to Threads, Facebook, and Instagram. The same center also runs the Craft City Rush game.',
  brandName: 'GO Marketing Center',
  titleJoin: ' | ',
  langGroup: 'Language',
  nav: {
    home: 'Home',
    posting: 'Posting',
    proof: 'Results',
    show: 'Podcast',
    game: 'Game',
    center: 'How it works',
    login: 'Log in',
    enter: 'Open the center',
  },
  footer: {
    posting: 'Go Posting',
    privacy: 'Privacy',
    rules: 'Game rules',
    enter: 'Open the center',
    teamLogin: 'Team login',
  },
  common: {
    loading: 'Loading…',
    aiEditor: (name: string) => `AI editor ${name}`,
    viewPost: 'View this post',
    postSoon: 'The latest post is being prepared.',
  },
  brands: [
    {
      name: 'TaskGo',
      editorName: 'Ahao',
      tagline: 'Simpler, smarter project management for construction crews',
      body: 'A job-site system for crews, general contractors, and repair teams. Repair dispatch, site surveys, quotes, progress photos, and billing all sit on one work order. Crews get the notice on LINE.',
      cta: 'Start a 14-day trial',
    },
    {
      name: 'Homigo',
      editorName: 'Xiaomi',
      tagline: 'Not another spreadsheet for houses — a house that runs itself',
      body: 'A rental platform for landlords and property managers. Listings, viewings, leases, move-in, rent reminders, and tenant repairs all connect to the tenant on LINE.',
      cta: 'Start free, no card required',
    },
    {
      name: 'Washgo',
      editorName: 'Ale',
      tagline: 'Laundry pickup and delivery, handled by Washgo',
      body: 'Pickup-and-delivery laundry for shops and customers. Order on LINE, pickup at the door, wash-status updates, and delivery confirmation — a shop can take online orders without building its own app.',
      cta: 'Visit the Washgo site',
    },
  ],
  modules: [
    { title: 'Brand workspace', body: 'One dashboard per brand: items waiting for review, today’s posts, a performance snapshot, and the to-do list.' },
    { title: 'Content studio and review', body: 'AI drafts copy and images from the brand rules. Nothing publishes until someone approves, edits, rejects, or postpones it. Every version is kept.' },
    { title: 'Publish once, three networks', body: 'Threads, Facebook, and Instagram go out through the official APIs. Long SEO articles can also be pushed to each brand blog.' },
    { title: 'Calendar and best times', body: 'A cross-brand calendar suggests a posting time for each network from past engagement.' },
    { title: 'AI editor team', body: 'Ahao, Xiaomi, and Ale each have a voice and a brand knowledge base. They handle daily posts, Threads replies, and community interaction.' },
    { title: 'Brand intelligence', body: 'Positioning, tone, product facts, and the image library live in one place. Every AI draft has to follow them.' },
    { title: 'Market signals', body: 'Industry news, policy, and trending topics are collected, tagged when they touch a brand, and turned into content ideas.' },
    { title: 'SEO / GEO', body: 'Keyword and long-form planning, plus work aimed at being cited by AI answer engines.' },
    { title: 'Support knowledge', body: 'Product docs become an embeddable help widget. Common questions get an AI answer first.' },
    { title: 'Podcast and short video', body: 'Episode management, 9:16 cuts, burned-in subtitles, and voiceover, reused as social assets.' },
    { title: 'Events and check-in', body: 'Event pages, online registration, QR tickets, and on-site scan check-in.' },
    { title: 'Meetings, decisions, collaboration', body: 'AI meeting notes, decision tracking, and cross-brand schedules, so the team can see who is doing what.' },
    { title: 'Performance and learning', body: 'Engagement from each network is rolled up. Topics and formats that worked feed the next round of drafts.' },
  ],
  flow: [
    { title: 'Collect', body: 'Market signals, brand knowledge, past results' },
    { title: 'Draft', body: 'An AI editor writes copy and images in the brand voice' },
    { title: 'Review', body: 'A person approves, edits, or sends it back' },
    { title: 'Publish', body: 'Scheduled or one-click to social and the site' },
    { title: 'Learn', body: 'Results come back, so the next post is sharper' },
  ],
  press: {
    source: 'Economic Daily News',
    meta: (date: string, name: string) => `Economic Daily News · ${date} · ${name}`,
    items: [
      { title: 'Digital tools for everyone: TaskGo helps crews keep job information in the open', note: 'Crews photograph the work and report by voice. Site records no longer depend on paper.' },
      { title: 'Inforcraft (匠管) enters proptech with Dataa and launches Homigo, a smart rental platform', note: 'The work-order practice from TaskGo extends into rentals. Landlords and tenants file repairs on LINE.' },
      { title: 'Traditional laundries try an AI shift: Washgo lands in central Taiwan and opens the brand', note: 'Intake, quality check, and delivery are one flow, already live in laundry shops in central Taiwan.' },
    ],
  },
  podcast: {
    coverAlt: 'GO Trio Talk: Ahao, Xiaomi, and Ale',
    title: 'GO Trio Talk',
    body: 'Ahao from the job site, Xiaomi the property manager, and Ale from the laundry shop talk each week about crews, rentals, and laundry. The voices, the scripts, and the publishing all come out of this marketing center.',
    latest: (date: string) => (date ? `Latest episode · ${date}` : 'Latest episode'),
    listen: 'Play this episode',
    soundon: 'Listen on SoundOn',
    feeds: ['SoundOn', 'YouTube', 'Spotify'],
    originalNote: 'The episode title and summary below are in the original Chinese.',
  },
  integrations: [
    { title: 'TaskGo close-out report: Craft City playback', body: 'When a repair job closes, the system turns dispatch, arrival, the work, and acceptance into a Craft City Rush animation. The client can see what was fixed.' },
    { title: 'Washgo order tracking: Craft City playback', body: 'When a customer checks a laundry order, pickup, wash, quality check, and return play through as a Craft City animation. There is something to watch while the clothes are out.' },
  ],
  homePages: [
    { title: 'Go Posting', body: 'Crews do not have to run their own social accounts. Two posts a week, NT$999 a month.', cta: 'See the price' },
    { title: 'Posts and press', body: 'Cumulative posts, views, and interactions for three brands, plus the latest post and Economic Daily News.', cta: 'See the results' },
    { title: 'GO Trio Talk', body: 'A podcast made by the same center. Listen on SoundOn, YouTube, or Spotify.', cta: 'Listen' },
    { title: 'Craft City Rush', body: 'A short run after the shift. The same playback is wired into TaskGo close-out reports and Washgo tracking.', cta: 'Play a round' },
    { title: 'How the center runs', body: 'Ideas, drafts, review, publishing, learning. The posts crews see come out of this loop.', cta: 'See the flow' },
  ],
  home: {
    title: 'Inforcraft (匠管) AI marketing center',
    eyebrow: 'GO Marketing Center',
    h1a: 'The AI marketing center',
    h1b: 'Inforcraft (匠管) built for three brands',
    lead1: 'Inforcraft (匠管) runs TaskGo, Homigo, and Washgo at the same time. A team cannot staff three social accounts every day, so we built GO Marketing Center. It posts to Facebook, Instagram, and Threads on its own. Three editors — Ahao (阿豪), Xiaomi (小咪), and Ale (阿樂) — each keep a fixed persona and voice, and the same center produces a podcast.',
    lead2: 'We also built a short game, Craft City Rush (匠城出任務), for crews to unwind after a shift, and wired that same presentation into the TaskGo and Washgo products.',
    ctaGame: 'Play Craft City Rush',
    ctaPrice: 'Two posts a week, NT$999 a month',
    gameEyebrow: 'Play a round',
    gameTitle: 'Craft City Rush',
    gameSub: 'Ride to a TaskGo repair, deliver Homigo keys, and pick up Washgo laundry. A round starts in 90 seconds, with no sign-up. For a full screen, open the game page.',
    openGame: 'Open the full game',
    gameMore: 'Maps, leaderboard, and the in-product playback',
    postsEyebrow: 'Brand posts',
    postsTitle: 'Three AI editors, one brand each',
    postsSub: 'Each brand shows only its latest published post. An editor drafted it in that brand’s voice, and a person approved it before it went live.',
    priceEyebrow: 'For crews',
    priceTitle: 'Go Posting, NT$999 a month',
    priceSub: 'The same center that posts on its own can now write two posts a week for a crew or a shop. This is not a separate software subscription.',
    priceMeta: '2 posts a week · Facebook, Instagram, Threads',
    priceUnit: ' / month',
    priceNote: 'An AI editor writes them. A person reads each one before it goes live. There is no second plan.',
    priceCta: 'See the full price',
    priceAside: 'This center was built first to run the three brands of Inforcraft (匠管). A crew can look at those results, then decide whether Go should post for them.',
    priceProof: 'See how the three brands post',
    pagesEyebrow: 'By page',
    pagesTitle: 'Each part stands on its own',
  },
  results: {
    fail: 'The performance numbers could not be loaded. The latest posts and press coverage are still below.',
    loading: 'Loading results…',
    published: 'Posts to date',
    publishedHint: 'Across three networks',
    impressions: 'Views to date',
    since: (month: string | null) => (month ? `Times a post was seen, since ${month}` : 'Times a published post was seen'),
    last28Impressions: 'Views, last 28 days',
    last28Posts: (n: string) => `${n} posts in the last 28 days`,
    last28Interactions: 'Interactions, last 28 days',
    interactionDetail: (likes: string, comments: string, shares: string, saves: string) => `${likes} likes, ${comments} comments, ${shares} shares, ${saves} saves`,
    byBrand: 'Results by brand',
    allPublished: 'Posts to date',
    recentPublished: 'Posts, last 28 days',
    allImpressions: 'Views to date',
    recentImpressions: 'Views, last 28 days',
    recentInteractions: 'Interactions, last 28 days',
    mix: (likes: string, comments: string, shares: string, saves: string, clicks: string | null) => {
      const base = `${likes} likes · ${comments} comments · ${shares} shares · ${saves} saves`;
      return clicks ? `${base} · ${clicks} link clicks` : base;
    },
    byPlatform: 'How much each network contributes',
    platformPending: 'Views are still being pulled back from the network',
    platformCounts: (all: string, recent: string) => `${all} views to date · ${recent} in the last 28 days`,
    platformRecent: (published: string, interactions: string) => `${published} posts in the last 28 days · ${interactions} interactions`,
    footnote: (refreshedAt: string | null, threadsMain: boolean, clicks: string | null) => {
      let text = `Published counts refresh about every two minutes. Views and interactions are pulled from each network about once an hour${refreshedAt ? `, last pull ${refreshedAt}` : ''}. The numbers are official platform results and exclude ads. A piece published to several networks counts once per network.`;
      if (threadsMain) text += ' Most of the views we can see right now come from Threads.';
      if (clicks) text += ` Link clicks to date: ${clicks}.`;
      return text;
    },
  },
  trend: {
    aria: 'View trend, last eight weeks',
    title: 'How the three brands are being seen in Taiwan',
    sub: 'Posts from the last eight weeks, and how many times they have been seen so far. The audience is in Taiwan. This chart is posting performance.',
    total: 'Views, last eight weeks',
    chartAria: 'Eight-week view lines for three brands',
    tooltip: (week: string, n: string) => `${week}: seen ${n} times`,
    detail: (week: string, posts: string, views: string, interactions: string) => `The week of ${week}: ${posts} posts, seen ${views} times so far, ${interactions} interactions.`,
    split: (interactions: string) => `Views · ${interactions} interactions`,
    reach: 'Last 28 days: who was seen more',
    weeksAria: 'Choose a week',
  },
  map: { s: 'Small map', m: 'Medium map', l: 'Large map', t: 'Taiwan map' },
  board: {
    eyebrow: (map: string) => `Leaderboard · ${map}`,
    fallbackTitle: 'All-time board',
    season: (start: string, end: string, map: string, topN: number) => `${start} – ${end}. Top ${topN} on the ${map} can win`,
    onShiftNow: 'On a run now',
    totalPlays: 'Runs to date',
    totalMinutes: 'Minutes on the job',
    playerCount: 'Players',
    tabs: { rank: 'Board', live: 'Playing', loyal: 'Most active' },
    rankFail: 'The leaderboard could not be loaded. Try again shortly.',
    emptyRank: 'Nobody is on the board yet.',
    emptyLive: 'Nobody is on a run right now.',
    emptyLoyal: 'No regulars yet. They show up here after a finished run is submitted.',
    onShift: (stay: string) => `On the job ${stay}`,
    loyalMeta: (phone: string, minutes: number) => `${phone} · ${minutes} min`,
    rounds: (plays: number) => `${plays} runs`,
    rules: 'Rules and how to claim a prize',
    prizeOriginal: 'Prize details are shown in the original Chinese.',
    stay: (seconds: number) => (seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}m ${seconds % 60}s`),
  },
  gameFrame: {
    title: 'Craft City Rush',
    alt: 'Craft City Rush gameplay',
    play: 'Start',
    fullscreen: 'Full screen',
    hint: 'On a phone, full screen is the smoother way to play',
  },
  posting: {
    title: 'Go Posting',
    eyebrow: 'For crews and shops',
    h1a: 'Go Posting',
    h1b: 'NT$999 a month',
    lead: 'Inforcraft (匠管) uses this center to post for TaskGo, Homigo, and Washgo. The same practice is now open to crews and shops: you do not have to invent topics, write the copy, or remember to hit publish. Two posts a week, NT$999 a month.',
    cta: 'Tell us what you need',
    proof: 'See how the three brands post',
    only: 'One plan',
    unit: ' / month',
    heroNote: '2 posts a week, to Facebook, Instagram, and Threads.',
    posterAlt: 'GO Marketing Center card. AI finds material, shapes the idea, writes the copy, and schedules the post. The flow is research, AI analysis, draft, human review, scheduled publishing. Pilot partners are being recruited.',
    posterCaption: 'The card itself is in Chinese. The offer is two posts a week for NT$999 a month. The flow on the card is research, AI analysis, a draft, human review, then scheduled publishing.',
    tableEyebrow: 'Price',
    tableTitle: 'One plan. This table is the whole offer.',
    plan: [
      ['Plan', 'Go Posting'],
      ['Posts per week', '2'],
      ['Where they go', 'Facebook, Instagram, Threads'],
      ['Who writes', 'An AI editor, in the voice of your trade'],
      ['Before publish', 'A person reads it'],
      ['Monthly fee', 'NT$999'],
    ],
    tableNote: 'The price includes writing and publishing. There is no annual plan and no upsell tier.',
    includedTitle: 'What NT$999 includes',
    includedHead: ['Included', 'What that means'],
    included: [
      ['Two posts a week', 'About eight a month, not one a day'],
      ['Three networks', 'The same post can go to Facebook, Instagram, and Threads'],
      ['An editor writes', 'The center’s AI editor writes it. It is not a blank template for you to fill in'],
      ['A person reviews', 'Someone reads it before it goes out'],
    ],
    excludedTitle: 'What this fee does not include',
    excludedHead: ['Not included', 'What that means'],
    excluded: [
      ['Ads', 'No ad buying, and no guaranteed reach'],
      ['Video and podcast', 'We do not record a podcast or shoot video for you'],
      ['Website articles', 'No SEO articles for your site'],
      ['Software fees', 'This is not the TaskGo, Homigo, or Washgo subscription'],
    ],
    startEyebrow: 'How to start',
    startTitle: 'Leave a number. We will call you.',
    steps: [
      { title: 'Send the form', body: 'Name, mobile, and trade. Add a note if you want to say something first.' },
      { title: 'Match the voice', body: 'We use the center’s editor and write for your trade. We do not reuse the three brands’ existing posts.' },
      { title: 'Two a week', body: 'Written, reviewed, then published to your Facebook, Instagram, or Threads.' },
      { title: 'NT$999 a month', body: 'The same thing happens next month. If you do not want to continue, just tell us.' },
    ],
    contactNote: (email: string) => `The Inforcraft (匠管) team handles setup and renewal. This site does not take cards. You can also email ${email}.`,
  },
  inquiry: {
    website: 'Website',
    name: 'Name',
    phone: 'Mobile',
    phonePlaceholder: '09xxxxxxxx',
    line: 'LINE ID (optional)',
    linePlaceholder: 'Leave blank if you have none',
    trade: 'Trade or shop name',
    tradePlaceholder: 'e.g. electrical crew, laundry shop',
    message: 'Anything we should know first (optional)',
    messagePlaceholder: 'Service area, things we should not say, questions',
    duplicate: 'This number already left details today. We will still be in touch.',
    ok: 'Received. We will call this number.',
    fail: 'Could not send. Please try again.',
    sending: 'Sending…',
    submit: 'Send, and contact me',
  },
  proof: {
    title: 'Posts and press for three brands',
    eyebrow: 'Results',
    h1: 'What three brands published, and what it brought in',
    lead: 'Ahao runs TaskGo, Xiaomi runs Homigo, and Ale runs Washgo, on Facebook, Instagram, and Threads. Below is the combined result, then each brand’s latest post, then coverage in the Economic Daily News.',
    resultsEyebrow: 'Posting performance',
    resultsTitle: 'The whole picture, in one view',
    resultsSub: 'The last eight weeks of views, plus volume, views, and interactions for each brand. Published counts refresh about every two minutes. Views and interactions are pulled from the networks about once an hour, and the networks themselves can take a few more hours to finish the numbers.',
    postsEyebrow: 'Latest posts',
    postsTitle: 'The most recent post from each brand',
    postsSub: 'The persona stays fixed and the voices do not mix. Open a post to read the original. Titles and excerpts stay in Chinese.',
    pressEyebrow: 'Press',
    pressTitle: 'Three brands covered by the Economic Daily News',
    pressSub: 'Headlines below are translated so they can be read here. Dates are from the articles. Open the original for the full Chinese text — we do not reprint it.',
    read: 'Read the original',
    brandsEyebrow: 'Three brands',
    brandsTitle: 'Repairs, rentals, laundry — one editor each',
    fixedEditor: (name: string) => `Standing editor: ${name}`,
    cta: 'Want the same posting? See the NT$999 plan',
  },
  show: {
    title: 'GO Trio Talk',
    eyebrow: 'Podcast',
    h1: 'The center also makes a show',
    lead: 'GO Trio Talk is produced by the same center: the topic, the script, the three editors’ voices, then publishing on SoundOn. Crews, landlords, and laundry shops hear something they can use, not a product launch.',
    hostsTitle: 'Three hosts. The same personas as the posts.',
    hosts: {
      taskgo: 'From the job site. Quotes, dispatch, and the things on a client’s site that cannot be left as a verbal note.',
      homigo: 'A property manager. Leases, who pays for repairs, and how landlords and tenants say it clearly.',
      washgo: 'A laundry-shop clerk. Clothes, pickup and return, and what the shop does when a customer changes the order.',
    },
    note: 'This page shows only the latest episode. The full list is on SoundOn. Subscribe links do not show a contact email.',
    cta: 'See what else this center does',
  },
  center: {
    title: 'How the marketing center works',
    eyebrow: 'How it works',
    h1: 'Posts are not written on the spot',
    lead: 'Inforcraft (匠管) built GO Marketing Center to run three brands at once. Ideas come in, an editor drafts, a person reviews, it goes out, and the results come back. The post a crew sees on a social account has been through that loop.',
    flowTitle: 'From an idea to a result',
    modulesEyebrow: 'Modules',
    modulesTitle: 'What the marketing team opens every day',
    modulesSub: 'These are the center’s internal desks. The NT$999 plan does not hand you this back office. Go Posting uses the same writing and publishing, and what you receive is two reviewed posts a week.',
    cta: 'See what NT$999 includes',
    show: 'Listen to GO Trio Talk',
  },
  game: {
    title: 'Craft City Rush',
    eyebrow: 'A game challenge',
    h1: 'After the shift, run one route and unwind',
    lead: 'Craft City Rush is a short game for crews: ride to a TaskGo repair, deliver Homigo keys, pick up Washgo laundry. The game itself already runs in English, 日本語, Tiếng Việt, and Bahasa Indonesia, so someone can feel a Taiwan shift — the weather, the garbage truck, the street incidents — in their own language. Finished runs can reach the leaderboard. The same playback is wired into the TaskGo and Washgo products.',
    posterAlt: 'Craft City Rush in four languages: English, Japanese (匠シティ・ラッシュ), Vietnamese, and Indonesian. The same Taiwan street, with the slow sign reading SLOW, 徐行, CHẬM, and PELAN.',
    posterCaption: 'The same Taiwan street. English, 日本語, Tiếng Việt, and Bahasa Indonesia can all start a shift.',
    mapTitle: 'How the maps work',
    steps: [
      { title: 'Small map', body: '90 seconds. Learn to take a job, check in, and head back.' },
      { title: 'Medium and large maps', body: 'More jobs. Weather and street conditions change every run.' },
      { title: 'Taiwan map', body: 'A hidden map that opens only when you invite a friend.' },
      { title: 'Leaderboard', body: 'A nickname goes on the board. The phone number is masked. A higher run of revenue has a better chance at a prize.' },
    ],
    embedTitle: 'Already playing inside the products',
    embedSub: 'When a job closes or someone checks progress, the flow plays below as a Craft City animation. The client does not have to press open to see how dispatch, the work, and the laundry steps connect.',
    demoNote: 'A demo environment. Not a real customer or a real job.',
    openFull: 'Open the full view',
    cta: 'See Go Posting',
  },
  week: {
    eyebrow: 'This month',
    title: 'This month’s total is still climbing',
    sub: 'The numbers are real runs, and the month turns over on Taipei time. Each bar is the month added up through that day, so the bars only get taller. Some days are busy and some are quiet. What matters is the month as a whole.',
    fail: 'This month’s numbers could not be loaded.',
    fallbackLabel: 'This month’s total is still climbing',
    todayAdded: (n: string) => ` Another ${n} runs came in today.`,
    plays: 'Runs this month',
    done: 'Finished runs',
    players: 'Unique players',
    stayLabel: 'Time on the job',
    previousFallback: 'Last month',
    previousMonthRuns: (name: string) => `Runs in all of ${name}`,
    jobs: 'Jobs completed in the game',
    barsAria: 'Cumulative runs this month',
    today: 'Today',
    cumulativeNote: 'The number on a bar is the total through that day, not that day alone.',
    jobTaskgo: (n: string) => `TaskGo repairs ${n}`,
    jobHomigo: (n: string) => `Homigo key drops ${n}`,
    jobWashgo: (n: string) => `Washgo pickups ${n}`,
    stay: (minutes: number) => {
      if (minutes < 60) return `${minutes} min`;
      const hours = minutes / 60;
      const shown = hours >= 10 ? Math.round(hours).toLocaleString('en-US') : hours.toFixed(1);
      return `${shown} hr`;
    },
    story: (input) => {
      const name = MONTHS[input.month] || 'This month';
      const prev = input.month === 1 ? 12 : input.month - 1;
      const previousLabel = MONTHS[prev] || 'Last month';
      const today = `Another ${input.today} runs came in today.`;
      if (input.previousPlays <= 0) {
        return {
          label: 'This month’s total is still climbing',
          detail: `${input.dayCount} days into ${name}, ${input.current} runs so far. The bars are cumulative, so they only grow. ${today}`,
          previousLabel,
        };
      }
      if (input.level === 'steady') {
        return {
          label: 'This month has already passed last month',
          detail: `${name} is only ${input.dayCount} days in, with ${input.current} runs — already more than all of ${previousLabel} (${input.previous} runs). ${today}`,
          previousLabel,
        };
      }
      return {
        label: 'This month’s total is still climbing',
        detail: `${input.dayCount} days into ${name}, ${input.current} runs. All of ${previousLabel} was ${input.previous} runs. Daily volume moves around; this chart is the running total. ${today}`,
        previousLabel,
      };
    },
  },
  scenes: {
    eyebrow: 'On this shift',
    title: 'The jobs and the street incidents change every run',
    sub: 'In 90 seconds you take three kinds of jobs, and ordinary Taiwan shows up at random. The pictures below are what players capture at the end of a run. The next one only appears if you play.',
    incidentsAlt: 'Random incidents in Craft City Rush: stray dogs, a police checkpoint, a garbage truck, an empty tank, and bubble tea.',
    incidentsCaption: 'Stray dogs, a checkpoint, the garbage truck, fuel, bubble tea. Any of these can show up on a shift.',
    momentsAlt: 'Craft City Rush moments: surrounded by stray dogs, delivering laundry in a snowy Kaohsiung, the whole lane running when the garbage truck rings, and four scooters in the garage.',
    momentsCaption: 'A finished run captures one moment. Dogs, laundry, the garbage truck — and you can switch to your own scooter.',
    doneLabel: 'Completed by players this month',
    times: (n: string) => `${n} times`,
    more: 'Also a fire truck, a crane, a stalled bus, a street music video, a pop-up market, standing water, and a fallen tree. 21 random conditions. You only find out which one by playing.',
    cta: 'Start a run',
    tasks: [
      { title: 'Repair dispatch', body: 'Stop at the site, check in by GPS, do the work, and upload photos.' },
      { title: 'Key handover', body: 'Deliver the keys to the new tenant. When the lights come on, that unit is moved in.' },
      { title: 'Laundry round', body: 'Pick up clothes along the route, take them to be washed, and bring them back.' },
    ],
    items: [
      { title: 'Stray dogs', line: 'Surrounded by local dogs, the crew gives up on the spot' },
      { title: 'Police checkpoint', line: 'Stopping for the check pays a bonus. Blowing through it is a fine' },
      { title: 'Garbage truck', line: 'Beethoven rings and the whole lane starts running' },
      { title: 'Bubble tea', line: 'One drink, then a few seconds at full speed' },
      { title: 'Chickens in the road', line: 'A flock takes the lane. Every vehicle waits' },
      { title: 'Cat under the scooter', line: 'The most important job in the city: get the cat out' },
      { title: 'Election motorcade', line: 'The convoy takes the whole road and hands the rider a flyer' },
      { title: 'Temple procession', line: 'Firecrackers and a parade pass by. A wish for a safe end of shift' },
      { title: 'Wedding convoy', line: 'Follow along and you might get wedding candy' },
      { title: 'Delivery swarm', line: 'Rush hour in the shopping streets. The rider is stuck in the middle' },
      { title: 'Sudden downpour', line: 'It was sunny at the door. Halfway there, the sky goes black' },
      { title: 'A huge pothole', line: 'Hit it at full speed and the toolbox nearly flies off' },
      { title: 'Roadworks ahead', line: 'The map says go straight. The fence says otherwise' },
      { title: 'Ambulance', line: 'Yielding pays a bonus. Blocking it costs points' },
      { title: 'School dismissal', line: 'Students and parents fill the junction. Slow down' },
    ],
  },
  wishes: {
    eyebrow: 'Board',
    title: 'If you want a feature, leave it here',
    sub: 'Finished a run with an idea? Write it down. A new map, a new job, or a street incident you still want to meet. A nickname is optional.',
    kindGroup: 'Note type',
    kinds: { feature: 'A feature I want', bug: 'A problem I hit', cheer: 'A note for the crew' },
    nickname: 'Nickname',
    nicknamePlaceholder: 'Optional, up to 12 characters',
    body: 'Your note',
    bodyPlaceholder: 'e.g. more night markets on the Taiwan map, and a faster garbage truck',
    company: 'Company',
    sending: 'Sending…',
    submit: 'Post to the board',
    ok: 'Got it. Other players can see it and press “I want this too.”',
    fail: 'Could not send. Please try again shortly.',
    cannotSupport: 'That button is not available right now',
    newest: 'Newest',
    hottest: 'Most wanted',
    empty: 'The first feature request is waiting for you.',
    support: (n: number) => `I want this too ${n}`,
  },
};
