import type { PublicCopy } from './zh';

/** 投資家向けの公開マーケティングサイト日本語。 */
export const ja: PublicCopy = {
  metaDescription: 'GO マーケティングセンターは、TaskGo・Homigo・Washgo の AI マーケティング基盤です。AI 編集がブランドごとの口調で原稿を作り、人が確認してから Threads、Facebook、Instagram に出します。同じセンターでゲーム「匠シティ・ラッシュ」も動いています。',
  brandName: 'GO マーケティングセンター',
  titleJoin: '｜',
  langGroup: '言語',
  nav: {
    home: 'ホーム',
    posting: '投稿代行',
    proof: '成果',
    show: 'Podcast',
    game: 'ゲーム',
    center: '仕組み',
    login: 'ログイン',
    enter: 'センターを開く',
  },
  footer: {
    posting: '投稿代行',
    privacy: 'プライバシー',
    rules: 'ゲーム規約',
    enter: 'センターを開く',
    teamLogin: 'チームログイン',
  },
  common: {
    loading: '読み込み中…',
    aiEditor: (name: string) => `AI 編集 ${name}`,
    viewPost: 'この投稿を見る',
    postSoon: '最新の投稿を準備しています。',
  },
  brands: [
    {
      name: 'TaskGo',
      editorName: 'アハオ',
      tagline: '工事の現場管理を、もっと簡単に、もっとスマートに',
      body: '工事班、元請、修繕チーム向けの現場管理です。修理の手配、現地調査、見積、施工写真、請求と完了が同じ作業伝票に載ります。現場には LINE で通知が届きます。',
      cta: '14 日間無料で試す',
    },
    {
      name: 'Homigo',
      editorName: 'シャオミ',
      tagline: '家を管理するのではなく、家が自分で回る仕組み',
      body: '大家と賃貸管理会社向けのプラットフォームです。物件掲載、内見、契約、入居、家賃の知らせ、入居者の修繕依頼を、LINE で入居者とつなぎます。',
      cta: '無料ではじめる。カード登録なし',
    },
    {
      name: 'Washgo',
      editorName: 'アーレ',
      tagline: '衣類の集配は、Washgo に任せる',
      body: 'クリーニング店と利用客向けの集配サービスです。LINE で注文し、自宅で受け取り、洗濯の進み具合を知らせ、届けてサインをもらいます。店は自前のアプリを作らなくてもネット注文を受けられます。',
      cta: 'Washgo のサイトへ',
    },
  ],
  modules: [
    { title: 'ブランド作業台', body: 'ブランドごとに一つの画面。確認待ち、今日の公開、成果の要約、やることが一度に見えます。' },
    { title: 'コンテンツと確認', body: 'AI がブランドのルールに沿って文と画像を作ります。承認、修正、差し戻し、延期を経てから公開し、版は残します。' },
    { title: '一度の操作で三つのSNS', body: 'Threads、Facebook、Instagram は公式 API で直接出します。SEO の長文は各ブランドのブログにも渡せます。' },
    { title: '予定表と出す時間', body: 'ブランドをまたいだ投稿カレンダーが、過去の反応から各 SNS の出す時間を提案します。' },
    { title: 'AI 編集チーム', body: 'アハオ、シャオミ、アーレはそれぞれ口調とブランド知識を持ち、日常の投稿、Threads の返信、コミュニティ対応を担います。' },
    { title: 'ブランドの知識庫', body: 'ポジション、口調、製品情報、素材画像を一か所で管理します。AI の出力はすべてこれを基準にします。' },
    { title: '市場のシグナル', body: '業界ニュース、制度、話題を集め、ブランドに関係するものを印づけて、投稿の題材にします。' },
    { title: 'SEO / GEO', body: 'キーワードと長文の企画に加え、AI の回答エンジンに引用されるための最適化をします。' },
    { title: 'サポート知識', body: '製品の説明を、サイトに埋め込めるサポート窓口にします。よくある質問は AI が先に答えます。' },
    { title: 'Podcast と短尺動画', body: 'エピソード管理、9:16 の短尺、焼き込み字幕、ナレーションを、SNS 素材としても使います。' },
    { title: 'イベント受付', body: 'イベントページ、オンライン申込、QR チケット、当日の読み取り受付まで一連です。' },
    { title: '会議、決定、共同作業', body: '議事録の AI 要約、決定の追跡、ブランドをまたいだ日程で、誰が何をしているかが見えます。' },
    { title: '成果と学習', body: '各 SNS の反応をまとめ、伸びた題材と形式を次の生成に戻します。' },
  ],
  flow: [
    { title: '集める', body: '市場の情報、ブランド知識、過去の成果' },
    { title: '作る', body: 'AI 編集がブランドの口調で文と画像を作る' },
    { title: '見る', body: '人が承認、修正、または差し戻す' },
    { title: '出す', body: 'SNS とサイトへ、予約またはワンクリック' },
    { title: '学ぶ', body: '成果が戻り、次の投稿がより正確になる' },
  ],
  press: {
    source: '経済日報',
    meta: (date: string, name: string) => `経済日報・${date}・${name}`,
    items: [
      { title: 'デジタルツールを現場へ。匠管 TaskGo が工事情報を見えるようにする', note: '職人はスマホで写真を撮り、音声で報告します。施工記録は紙に頼りません。' },
      { title: '匠管が達観と PropTech へ。賃貸管理プラットフォーム Homigo を発表', note: 'TaskGo の作業伝票の経験を賃貸管理へ広げ、大家と入居者は LINE で修繕を依頼できます。' },
      { title: '町のクリーニング店も AI へ。匠管 Washgo が中部で稼働、ブランド参加を開放', note: '受け取り、品質確認、配送を一つの流れにし、中部のクリーニング店で既に動いています。' },
    ],
  },
  podcast: {
    coverAlt: 'GO 三人編集の雑談：アハオ、シャオミ、アーレ',
    title: 'GO 三人編集の雑談',
    body: '現場出身のアハオ、賃貸管理のシャオミ、クリーニング店のアーレが、毎週、工事、賃貸、洗濯の話題を話します。三人の声、台本、公開はすべてこのセンターが作っています。',
    latest: (date: string) => (date ? `最新回・${date}` : '最新回'),
    listen: 'この回を聴く',
    soundon: 'SoundOn で聴く',
    feeds: ['SoundOn', 'YouTube', 'Spotify'],
    originalNote: '下の回のタイトルと要約は、原文の中国語のままです。',
  },
  integrations: [
    { title: 'TaskGo 完了報告：匠シティ再生', body: '修繕が終わると、手配、到着、施工、検収が匠シティ・ラッシュのアニメになります。施主は、今回何を直したかが一目で分かります。' },
    { title: 'Washgo 配送追跡：匠シティ再生', body: 'お客が洗濯の進み具合を見ると、受け取り、洗濯、検品、返送が匠シティのアニメで流れます。衣類を待っている間にも見るものがあります。' },
  ],
  homePages: [
    { title: 'Go 投稿代行', body: '工事班が自分で SNS を見守らなくてよい。週 2 本、月額 NT$999。', cta: '料金を見る' },
    { title: '三ブランドの投稿と報道', body: '三ブランドの累計投稿、表示、反応に、最新投稿と経済日報を加えます。', cta: '成果を見る' },
    { title: '三人編集の雑談', body: '同じセンターが作った Podcast。SoundOn、YouTube、Spotify で聴けます。', cta: '聴く' },
    { title: '匠シティ・ラッシュ', body: '仕事のあと、一回走る。ゲームの見せ方は TaskGo の完了報告と Washgo の追跡にも入っています。', cta: '一回遊ぶ' },
    { title: 'センターの回り方', body: '題材、生成、確認、公開、学習。現場が見る投稿は、この循環から出ます。', cta: '流れを見る' },
  ],
  home: {
    title: '匠管の AI マーケティングセンター',
    eyebrow: 'GO Marketing Center',
    h1a: '三つのブランドのために',
    h1b: '匠管が作った AI マーケティングセンター',
    lead1: '匠管は TaskGo、Homigo、Washgo を同時に運営しています。人が毎日三つの SNS を見守るのは無理なので、GO マーケティングセンターを作りました。Facebook、Instagram、Threads へ自分で投稿します。三人の編集、アハオ（阿豪）、シャオミ（小咪）、アーレ（阿樂）は、それぞれ人設と口調が固定で、Podcast もこのセンターが作ります。',
    lead2: '仕事のあと職人が一息つける小さなゲーム「匠シティ・ラッシュ」（匠城出任務）も作り、その見せ方を TaskGo と Washgo のシステムに接続しました。',
    ctaGame: '匠シティ・ラッシュを遊ぶ',
    ctaPrice: '週 2 本、月額 NT$999',
    gameEyebrow: 'まず一回',
    gameTitle: '匠シティ・ラッシュ',
    gameSub: 'バイクで TaskGo の修理、Homigo の鍵届け、Washgo の衣類回収に向かいます。90 秒で始められ、登録は不要です。全画面で遊ぶなら、ゲームページを開いてください。',
    openGame: 'ゲームを全画面で開く',
    gameMore: 'マップ、ランキング、システム内の再生',
    postsEyebrow: 'ブランド投稿',
    postsTitle: '三人の AI 編集が、ブランドを一つずつ担当',
    postsSub: '各ブランドには、公開済みの最新 1 本だけを置いています。編集がブランドの口調で作り、チームが確認してから出しています。',
    priceEyebrow: '工事班向け',
    priceTitle: 'Go 投稿代行は、月額 NT$999',
    priceSub: '自分で投稿するこのセンターが、工事班や店舗の週 2 本も書きます。別システムの月額ではありません。',
    priceMeta: '週 2 本 · Facebook、Instagram、Threads',
    priceUnit: '／月',
    priceNote: 'AI 編集が書き、公開前に人が見ます。もう一つのプランはありません。',
    priceCta: '料金の全体を見る',
    priceAside: 'このセンターは、まず匠管自身の三ブランドを運営するために作りました。工事班は成果を見てから、Go に任せるか決められます。',
    priceProof: '三ブランドの投稿成果を見る',
    pagesEyebrow: 'ページごとに',
    pagesTitle: 'どの部分も、単独で読めます',
  },
  results: {
    fail: '成果の数字を読み込めませんでした。下には最新の投稿と報道が残っています。',
    loading: '成果を読み込み中…',
    published: '累計公開',
    publishedHint: '三つの SNS の合計',
    impressions: '累計表示',
    since: (month: string | null) => (month ? `${month}からの表示回数` : '公開済み投稿が見られた回数'),
    last28Impressions: '直近 28 日の表示',
    last28Posts: (n: string) => `直近 28 日に ${n} 本`,
    last28Interactions: '直近 28 日の反応',
    interactionDetail: (likes: string, comments: string, shares: string, saves: string) => `いいね ${likes}、コメント ${comments}、シェア ${shares}、保存 ${saves}`,
    byBrand: 'ブランドごとの成果',
    allPublished: '累計公開',
    recentPublished: '直近 28 日の公開',
    allImpressions: '累計表示',
    recentImpressions: '直近 28 日の表示',
    recentInteractions: '直近 28 日の反応',
    mix: (likes: string, comments: string, shares: string, saves: string, clicks: string | null) => {
      const base = `いいね ${likes} · コメント ${comments} · シェア ${shares} · 保存 ${saves}`;
      return clicks ? `${base} · リンククリック ${clicks}` : base;
    },
    byPlatform: 'SNS ごとの貢献',
    platformPending: '表示回数は、まだ SNS から回収中です',
    platformCounts: (all: string, recent: string) => `累計表示 ${all} · 直近 28 日 ${recent}`,
    platformRecent: (published: string, interactions: string) => `直近 28 日の公開 ${published} 本 · 反応 ${interactions}`,
    footnote: (refreshedAt: string | null, threadsMain: boolean, clicks: string | null) => {
      let text = `公開本数は約 2 分ごとに更新します。表示と反応は約 1 時間ごとに各 SNS から回収します${refreshedAt ? `。直近の回収は ${refreshedAt}` : ''}。数字は各 SNS の公式成果で、広告は含みません。一つの内容を複数の SNS に出した場合、SNS ごとに 1 本と数えます。`;
      if (threadsMain) text += 'いま見えている表示の多くは Threads からです。';
      if (clicks) text += `別途、累計リンククリックは ${clicks} です。`;
      return text;
    },
  },
  trend: {
    aria: '直近 8 週の表示推移',
    title: '三ブランドが台湾で見られている推移',
    sub: '直近 8 週に出した投稿が、これまでに見られた回数です。受け手は台湾にいます。この図は投稿の成果です。',
    total: '直近 8 週の表示',
    chartAria: '直近 8 週、三ブランドの表示折れ線',
    tooltip: (week: string, n: string) => `${week} に ${n} 回見られた`,
    detail: (week: string, posts: string, views: string, interactions: string) => `${week} の週に ${posts} 本出し、これまでに ${views} 回見られ、反応は ${interactions} 回です。`,
    split: (interactions: string) => `表示 · 反応 ${interactions}`,
    reach: '直近 28 日、より見られたのはどこか',
    weeksAria: '週を選ぶ',
  },
  map: { s: '小マップ', m: '中マップ', l: '大マップ', t: '台湾マップ' },
  board: {
    eyebrow: (map: string) => `ランキング・${map}`,
    fallbackTitle: '全体ランキング',
    season: (start: string, end: string, map: string, topN: number) => `期間 ${start} – ${end}。${map}の上位 ${topN} 名が受賞`,
    onShiftNow: 'いま稼働中',
    totalPlays: '累計プレイ',
    totalMinutes: '累計稼働（分）',
    playerCount: 'プレイヤー数',
    tabs: { rank: '順位', live: 'プレイ中', loyal: '常連' },
    rankFail: 'ランキングを読み込めませんでした。しばらくしてからもう一度。',
    emptyRank: 'まだ誰も載っていません。',
    emptyLive: 'いま走っている人はいません。',
    emptyLoyal: 'まだ常連はいません。プレイ結果を送ると、ここに出ます。',
    onShift: (stay: string) => `稼働 ${stay}`,
    loyalMeta: (phone: string, minutes: number) => `${phone}・${minutes} 分`,
    rounds: (plays: number) => `${plays} 回`,
    rules: '規約と受け取り方',
    prizeOriginal: '賞品の説明は、原文の中国語のままです。',
    stay: (seconds: number) => (seconds < 60 ? `${seconds} 秒` : `${Math.floor(seconds / 60)} 分 ${seconds % 60} 秒`),
  },
  gameFrame: {
    title: '匠シティ・ラッシュ',
    alt: '匠シティ・ラッシュの画面',
    play: '開始',
    fullscreen: '全画面で開く',
    hint: 'スマホは「全画面で開く」がいちばん操作しやすいです',
  },
  posting: {
    title: 'Go 投稿代行',
    eyebrow: '工事班と店舗へ',
    h1a: 'Go 投稿代行',
    h1b: '月額 NT$999',
    lead: '匠管はこのセンターで TaskGo、Homigo、Washgo の投稿を出しています。同じやり方を、工事班と店舗にも開きます。題を考え、文を書き、公開ボタンを押す必要はありません。週 2 本、月額 NT$999 です。',
    cta: '要望を送る。こちらから連絡します',
    proof: '三ブランドの出し方を見る',
    only: 'この一種類だけ',
    unit: '／月',
    heroNote: '週 2 本を、Facebook、Instagram、Threads へ。',
    posterAlt: 'GO マーケティングセンターの案内。AI が資料を探し、内容を考え、文を作り、予約投稿します。流れは資料検索、AI 分析、原稿、人の確認、予約公開です。試験パートナーを募っています。',
    posterCaption: '画像の文字は中国語です。内容は週 2 本、月額 NT$999。図の流れは、資料検索、AI 分析、原稿、人の確認、予約公開です。',
    tableEyebrow: '料金表',
    tableTitle: 'プランは一つ。この表で足ります。',
    plan: [
      ['プラン', 'Go 投稿代行'],
      ['週の本数', '2 本'],
      ['出す先', 'Facebook、Instagram、Threads'],
      ['誰が書くか', 'AI 編集が、その業種の口調で書く'],
      ['公開前', '人が見てから出す'],
      ['月額', 'NT$999'],
    ],
    tableNote: '料金には執筆と公開が含まれます。年契約もなく、追加プランもありません。',
    includedTitle: 'NT$999 に含まれるもの',
    includedHead: ['含む', '説明'],
    included: [
      ['週 2 本の投稿', '月におよそ 8 本。毎日 1 本ではありません'],
      ['三つの SNS', '同じ 1 本を Facebook、Instagram、Threads に出せます'],
      ['編集が書く', 'センターの AI 編集が書きます。空欄のひな型を自分で埋めるものではありません'],
      ['人が確認', '出す前に、一度目を通します'],
    ],
    excludedTitle: 'この料金に含まれないもの',
    excludedHead: ['含まない', '説明'],
    excluded: [
      ['広告', '広告の購入も、表示回数の保証もありません'],
      ['撮影と Podcast', 'Podcast の収録や動画撮影は含みません'],
      ['サイトの長文', '公式サイトの SEO 記事は含みません'],
      ['システムの月額', 'TaskGo、Homigo、Washgo のソフト利用料ではありません'],
    ],
    startEyebrow: '始め方',
    startTitle: '連絡先を残してください。こちらから電話します。',
    steps: [
      { title: 'フォーム', body: '氏名、携帯、業種。先に伝えたいことがあれば備考へ。' },
      { title: '口調を合わせる', body: 'センターの編集が、その業種向けに書きます。三ブランドの既存文を使い回しません。' },
      { title: '週 2 本', body: '書いて、確認して、Facebook、Instagram、または Threads に出します。' },
      { title: '月額 NT$999', body: '翌月も同じことをします。続けないときは、一声ください。' },
    ],
    contactNote: (email: string) => `開通と継続は匠管のチームが扱います。このサイトにカード決済はありません。メールは ${email} でも受け付けます。`,
  },
  inquiry: {
    website: 'サイト',
    name: '氏名',
    phone: '携帯',
    phonePlaceholder: '09xxxxxxxx',
    line: 'LINE ID（任意）',
    linePlaceholder: 'なければ空欄',
    trade: '業種または店名',
    tradePlaceholder: '例：電気工事、クリーニング店',
    message: '先に伝えておきたいこと（任意）',
    messagePlaceholder: '対応エリア、言ってはいけないこと、先に聞きたいこと',
    duplicate: 'この番号は今日すでに登録されています。あらためて連絡します。',
    ok: '受け取りました。この番号にご連絡します。',
    fail: '送信できませんでした。もう一度お試しください。',
    sending: '送信中…',
    submit: '送信して、連絡をもらう',
  },
  proof: {
    title: '三ブランドの投稿と報道',
    eyebrow: '成果',
    h1: '三つのブランドは、どれだけ出し、何を連れてきたか',
    lead: 'アハオが TaskGo、シャオミが Homigo、アーレが Washgo を担当し、Facebook、Instagram、Threads に出しています。まず三ブランドを合算した成果、次に各ブランドの最新 1 本、それから経済日報の報道です。',
    resultsEyebrow: '投稿の成果',
    resultsTitle: '全体の成果を、一度に見る',
    resultsSub: '直近 8 週の表示の推移と、三ブランドの本数、表示、反応が見られます。公開本数は約 2 分ごとに更新します。表示と反応は約 1 時間ごとに SNS から回収し、SNS 側の数字はさらに数時間遅れて揃うことがあります。',
    postsEyebrow: '最新の投稿',
    postsTitle: '各ブランドが最近出した 1 本',
    postsSub: '人設は固定で、口調は混ぜません。開くと原文が読めます。タイトルと抜粋は中国語のままです。',
    pressEyebrow: 'メディア',
    pressTitle: '経済日報が報じた三つのブランド',
    pressSub: '見出しは読むために訳しています。日付は記事のものです。全文は原文を開いてください。転載はしません。',
    read: '原文を読む',
    brandsEyebrow: '三つのブランド',
    brandsTitle: '修繕、賃貸、洗濯。それぞれに編集が一人',
    fixedEditor: (name: string) => `担当編集：${name}`,
    cta: '同じ投稿が必要なら、NT$999 のプランを見る',
  },
  show: {
    title: '三人編集の雑談',
    eyebrow: 'Podcast',
    h1: 'センターは、番組も作ります',
    lead: '「GO 三人編集の雑談」は同じセンターの出力です。題、台本、三人の声を作り、SoundOn に載せます。工事班、大家、クリーニング店が聴くのは、生活で使える話であって、製品発表会ではありません。',
    hostsTitle: '三人のホスト。人設は投稿と同じです。',
    hosts: {
      taskgo: '現場出身。見積、手配、施主の現場で口約束だけでは済まないことを話します。',
      homigo: '賃貸管理。契約、修繕の負担、大家と入居者がどう言い切るかを話します。',
      washgo: 'クリーニング店の店員。衣類、集配、お客が急に注文を変えたとき店がどう受けるかを話します。',
    },
    note: 'このページに置くのは最新の 1 回だけです。全話は SoundOn にあります。購読リンクに連絡先メールは出しません。',
    cta: 'このセンターがほかにできることを見る',
  },
  center: {
    title: 'マーケティングセンターの動き方',
    eyebrow: '仕組み',
    h1: '投稿は、その場の思いつきでは書きません',
    lead: 'GO マーケティングセンターは、匠管が三つのブランドを同時に運営するために作ったものです。題材が入り、編集が作り、人が確認し、公開し、成果が戻ってきます。工事班が SNS で見る 1 本は、この循環を通っています。',
    flowTitle: '題材から成果まで',
    modulesEyebrow: '機能',
    modulesTitle: 'マーケティングチームが毎日開くもの',
    modulesSub: 'これらはセンター内部の作業台です。NT$999 のプランで、この管理画面が別に開くわけではありません。投稿代行は同じ執筆と公開を使い、届くのは週 2 本、確認済みの投稿です。',
    cta: 'NT$999 に何が含まれるかを見る',
    show: '三人編集の雑談を聴く',
  },
  game: {
    title: '匠シティ・ラッシュ',
    eyebrow: 'ゲーム',
    h1: '仕事が終わったら、一回走って息を抜く',
    lead: '匠シティ・ラッシュは、工事班が遊ぶ小さなゲームです。バイクで TaskGo の修理、Homigo の鍵届け、Washgo の衣類回収に向かいます。ゲーム内の言語は English、日本語、Tiếng Việt、Bahasa Indonesia です。自分の言語で、台湾の一勤務——天気、ゴミ収集車、道の出来事——を体験できます。終わるとランキングに載れ、同じ見せ方は TaskGo と Washgo のシステムにも入っています。',
    posterAlt: '匠シティ・ラッシュの四言語。English の Craft City Rush、日本語の匠シティ・ラッシュ、Tiếng Việt、Bahasa Indonesia。同じ台湾の通りで、徐行の標識は SLOW、徐行、CHẬM、PELAN。',
    posterCaption: '同じ台湾の通りです。English、日本語、Tiếng Việt、Bahasa Indonesia のどれでも始められ、台湾で一勤務する感じを先に体験できます。',
    mapTitle: 'マップの進み方',
    steps: [
      { title: '小マップ', body: '90 秒。受注、打刻、帰路に慣れます。' },
      { title: '中マップ、大マップ', body: '仕事が増えます。天気と道の様子は、回ごとに違います。' },
      { title: '台湾マップ', body: '友人を招待しないと開かない隠しマップです。' },
      { title: 'ランキング', body: 'ニックネームで載ります。電話番号は伏せます。連続の売上ほど、賞に近づきます。' },
    ],
    embedTitle: 'すでにシステムへ入っている匠シティ再生',
    embedSub: '完了時や進捗確認では、流れが下で匠シティのアニメとして再生されます。お客は開き直さなくても、手配、施工、洗濯がどうつながるかを見られます。',
    demoNote: '試験環境の展示です。実在のお客や実在の案件ではありません。',
    openFull: '全体を別窓で開く',
    cta: 'Go 投稿代行を見る',
  },
  week: {
    eyebrow: '今月',
    title: '今月の累計は、まだ積み上がっています',
    sub: '数字は実際のプレイで、月の切り替えは台北時間です。棒は今月を一日ずつ足したものなので、高くなるだけです。日によって多い少ないはあります。見るのは今月の全体です。',
    fail: '今月の数字を読み込めませんでした。',
    fallbackLabel: '今月の累計は、まだ積み上がっています',
    todayAdded: (n: string) => ` 今日はさらに ${n} 回加わりました。`,
    plays: '今月の累計プレイ',
    done: '今月の完走',
    players: '今月の重複なしプレイヤー',
    stayLabel: '今月の滞在',
    previousFallback: '先月',
    previousMonthRuns: (name: string) => `${name}の1か月のプレイ`,
    jobs: '今月、ゲーム内で終えた仕事',
    barsAria: '今月の累計プレイ',
    today: '今日',
    cumulativeNote: '棒の数字は、その日までの累計です。その日だけではありません。',
    jobTaskgo: (n: string) => `TaskGo 修理 ${n}`,
    jobHomigo: (n: string) => `Homigo 鍵届け ${n}`,
    jobWashgo: (n: string) => `Washgo 集配 ${n}`,
    stay: (minutes: number) => {
      if (minutes < 60) return `${minutes} 分`;
      const hours = minutes / 60;
      const shown = hours >= 10 ? Math.round(hours).toLocaleString('ja-JP') : hours.toFixed(1);
      return `${shown} 時間`;
    },
    story: (input) => {
      const name = `${input.month}月`;
      const prev = input.month === 1 ? 12 : input.month - 1;
      const previousLabel = `${prev}月`;
      const today = `今日はさらに ${input.today} 回加わりました。`;
      if (input.previousPlays <= 0) {
        return {
          label: '今月の累計は、まだ積み上がっています',
          detail: `${name}は ${input.dayCount} 日が過ぎ、累計 ${input.current} 回です。棒は累計なので、日ごとに高くなるだけです。${today}`,
          previousLabel,
        };
      }
      if (input.level === 'steady') {
        return {
          label: '今月は、すでに先月を超えています',
          detail: `${name}はまだ ${input.dayCount} 日で、累計 ${input.current} 回。${previousLabel}の1か月（${input.previous} 回）をすでに超えています。${today}`,
          previousLabel,
        };
      }
      return {
        label: '今月の累計は、まだ積み上がっています',
        detail: `${name}は ${input.dayCount} 日が過ぎ、累計 ${input.current} 回です。${previousLabel}の1か月は ${input.previous} 回でした。日によって上下はあります。この図が見ているのは累計です。${today}`,
        previousLabel,
      };
    },
  },
  scenes: {
    eyebrow: 'この一勤務で出会うもの',
    title: '仕事と道の出来事は、回ごとに違います',
    sub: '90 秒で三種類の仕事を受け、道には台湾の日常がランダムに出ます。下は、プレイヤーが仕事終わりに撮る画面です。次の一枚は、ゲームに入らないと出ません。',
    incidentsAlt: '匠シティ・ラッシュのランダムイベント。野良犬の追跡、警察の検問、ゴミ収集車、燃料切れ、タピオカ。',
    incidentsCaption: '野良犬、検問、ゴミ収集車、給油、タピオカ。どれも、一勤務で起こり得ます。',
    momentsAlt: '名場面。野良犬に囲まれる、高雄が雪でも洗濯を届ける、ゴミ収集車の音で路地が走り出す、ガレージのバイク 4 台。',
    momentsCaption: '仕事が終わると名場面を一枚撮ります。野良犬、洗濯の配送、ゴミ収集車。自分のバイクにも替えられます。',
    doneLabel: '今月プレイヤーが完了',
    times: (n: string) => `${n} 回`,
    more: 'ほかに消防車、クレーン、止まったバス、路上の MV 撮影、臨時マーケット、道路の水たまり、倒木があります。ランダムな路況は 21 種。今日どれに当たるかは、一回遊んで初めて分かります。',
    cta: 'ゲームで一回走る',
    tasks: [
      { title: '修理の手配', body: '現場で一度止まり、GPS で打刻し、施工して、写真を上げます。' },
      { title: '鍵を届けて入居', body: '新しい入居者に鍵を渡します。明かりがつけば、その戸は入居です。' },
      { title: '衣類の集配', body: '道沿いの衣類を集め、洗いに出し、お客の手元へ戻します。' },
    ],
    items: [
      { title: '野良犬が追う', line: '野良犬に囲まれ、職人はその場で降参' },
      { title: '警察の検問', line: '止まって受ければボーナス。突っ切ると反則' },
      { title: 'ゴミ収集車', line: 'エリーゼが鳴ると、路地中が走る' },
      { title: 'タピオカ', line: '一杯飲むと、数秒だけ全速' },
      { title: '鶏が道を渡る', line: '鶏の群れが車道を占め、車は全部待つ' },
      { title: '車の下の猫', line: '街でいちばん大事な仕事は、猫を出すこと' },
      { title: '選挙カー', line: '車列が道を埋め、職人にビラが渡される' },
      { title: '廟の巡行', line: '爆竹と行列が通り、仕事終わりの無事を願う' },
      { title: '結婚式の車列', line: '後ろにつくと、引出物の菓子がもらえることがある' },
      { title: '配達の大群', line: '商店街のピーク。職人は挟まれて動けない' },
      { title: '突然の豪雨', line: '出るときは晴れ。途中で空が黒くなる' },
      { title: '大きな穴', line: '全速で落ち、工具箱が飛びそうになる' },
      { title: 'この先工事', line: 'ナビは直進。結果、フェンスにぶつかる' },
      { title: '救急車', line: '道を譲るとボーナス。ふさぐと減点' },
      { title: '学校の下校', line: '生徒と保護者で交差点が埋まる。ゆっくり走る' },
    ],
  },
  wishes: {
    eyebrow: '掲示板',
    title: '欲しい機能は、ここに残す',
    sub: '一回遊んで思いついたら、そのまま書いてください。新しいマップ、新しい仕事、道でまだ出会いたい出来事。ニックネームは空欄でも構いません。',
    kindGroup: '投稿の種類',
    kinds: { feature: '欲しい機能', bug: 'ぶつかった問題', cheer: '職人への一言' },
    nickname: 'ニックネーム',
    nicknamePlaceholder: '空欄可。12 字まで',
    body: '書きたいこと',
    bodyPlaceholder: '例：台湾マップに夜市を増やしたい。ゴミ収集車はもう少し速く',
    company: '会社',
    sending: '送信中…',
    submit: '掲示板に貼る',
    ok: '受け取りました。ほかのプレイヤーも見られ、「自分も欲しい」を押せます。',
    fail: '送信できませんでした。しばらくしてからもう一度。',
    cannotSupport: 'いまは押せません',
    newest: '新しい順',
    hottest: '欲しい人が多い順',
    empty: '最初の「欲しい機能」は、あなたの番です。',
    support: (n: number) => `自分も欲しい ${n}`,
  },
};
