/** 公開行銷站的繁體中文文案。英文與日文必須對齊這個物件的形狀。 */
export const zh = {
  metaDescription: 'GO 行銷中心是 TaskGo 匠管、Homigo、Washgo 共用的 AI 行銷營運系統：AI 小編依品牌口吻產出內容，審閱後一鍵發布到 Threads、Facebook、Instagram 與官網。還能玩「匠城出任務」遊戲挑戰排行榜。',
  brandName: 'GO 行銷中心',
  titleJoin: '｜',
  langGroup: '語言',
  nav: {
    home: '首頁',
    posting: 'Go幫你發文',
    proof: '品牌成果',
    show: 'Podcast',
    game: '遊戲',
    center: '怎麼運作',
    login: '登入',
    enter: '進入行銷中心',
  },
  footer: {
    posting: 'Go幫你發文',
    privacy: '隱私權政策',
    rules: '遊戲活動辦法',
    enter: '進入行銷中心',
    teamLogin: '團隊登入',
  },
  common: {
    loading: '載入中…',
    aiEditor: (name: string) => `AI 小編 ${name}`,
    viewPost: '看這則貼文',
    postSoon: '最近一則貼文準備中。',
  },
  brands: [
    {
      name: 'TaskGo 匠管',
      editorName: '阿豪',
      tagline: '讓工程專案管理更簡單、更智能',
      body: '給工班、統包與修繕團隊的案場管理系統。報修派工、場勘報價、施工照回報、請款結案都在同一條工單上，現場師傅用 LINE 就能接收通知。',
      cta: '免費試用 14 天',
    },
    {
      name: 'Homigo',
      editorName: '小咪',
      tagline: '不是管理房子，而是讓房子自己運作',
      body: '給房東與包租代管的租務平台。物件上架、看房、簽約交屋、收租提醒、房客報修，都能透過 LINE 與房客即時串起來。',
      cta: '免費開始，不綁信用卡',
    },
    {
      name: 'Washgo',
      editorName: '阿樂',
      tagline: '衣物送洗，交給 Washgo',
      body: '給洗衣店與消費者的收送洗服務。LINE 下單、到府收件、洗護進度通知、送回簽收，讓洗衣店不用另外做 App 也能接線上訂單。',
      cta: '前往 Washgo 官網',
    },
  ],
  modules: [
    { title: '品牌工作台', body: '每個品牌一個儀表板：待審內容、今日發布、成效摘要與待辦一眼看完。' },
    { title: '內容中心與審閱', body: 'AI 依品牌規範產出文案與配圖，經過核准、修改、退回、延期等審閱流程才發布，每一版都留紀錄。' },
    { title: '一鍵多平台發布', body: 'Threads、Facebook、Instagram 走官方 API 直接發布，官網 SEO 長文也能推到各品牌部落格。' },
    { title: '行程表與最佳時段', body: '跨品牌發文行程表，依歷史互動數據建議每個平台的發文時段。' },
    { title: 'AI 小編團隊', body: '阿豪、小咪、阿樂各有口吻與品牌知識，負責日常貼文、Threads 回覆與社群互動。' },
    { title: '品牌智慧庫', body: '品牌定位、語氣規範、產品資料與素材圖庫集中管理，所有 AI 產出都以此為準。' },
    { title: '市場情報與趨勢', body: '蒐集產業新聞、政策與熱門話題，自動標出與品牌相關的訊號，轉成內容題材。' },
    { title: 'SEO / GEO', body: '規劃關鍵字與長文主題，並針對 AI 搜尋引擎優化品牌被引用的機會。' },
    { title: '客服知識庫', body: '產品說明文件轉成可嵌入官網的客服小工具，常見問題由 AI 先回答。' },
    { title: 'Podcast 與短影音', body: 'Podcast 集數管理、剪成 9:16 短影音、燒錄字幕與配音，延伸成社群素材。' },
    { title: '活動報名與報到', body: '活動頁、線上報名、QR Code 電子票與現場掃碼報到一次完成。' },
    { title: '會議、決策與協作', body: '會議紀錄 AI 摘要、決策追蹤、跨品牌合作排程，讓團隊知道誰在做什麼。' },
    { title: '成效分析與學習', body: '彙整各平台互動數據，找出表現好的題材與格式，回饋到下一輪內容生成。' },
  ],
  flow: [
    { title: '蒐集', body: '市場情報、品牌知識、過往成效' },
    { title: '生成', body: 'AI 小編依品牌口吻產文案與圖' },
    { title: '審閱', body: '人工核准、修改或退回' },
    { title: '發布', body: '社群與官網排程或一鍵發布' },
    { title: '學習', body: '成效回流，下一篇更準' },
  ],
  press: {
    source: '經濟日報',
    meta: (date: string, name: string) => `經濟日報・${date}・${name}`,
    items: [
      { title: '數位工具平民化 匠管 Task Go 助攻工班資訊透明', note: '師傅用手機拍照、語音回報，施工紀錄不再靠紙本。' },
      { title: '匠管攜手達觀跨足 PropTech 市場 推出 Homigo 智慧租屋管理平台', note: '從 TaskGo 的工單經驗延伸到租屋管理，房東房客用 LINE 就能報修。' },
      { title: '傳統洗衣店也拚 AI 數位轉型！匠管 Washgo 中部落地、開放品牌加入', note: '收件、品管、收送串成一條流程，已在中部洗衣店實際上線。' },
    ],
  },
  podcast: {
    coverAlt: 'GO三小編熱聊：阿豪、小咪、阿樂',
    title: 'GO三小編熱聊',
    body: '工班出身的阿豪、包租管家小咪、洗衣店店員阿樂，每週聊工地、租屋、洗衣的熱門話題。三個人的聲音、腳本與上架都由行銷中心產出。',
    latest: (date: string) => (date ? `最新一集・${date}` : '最新一集'),
    listen: '收聽這一集',
    soundon: '到 SoundOn 收聽',
    feeds: ['SoundOn 訂閱', 'YouTube 訂閱', 'Spotify 訂閱'],
    originalNote: '',
  },
  integrations: [
    { title: 'TaskGo 結案報告：匠城呈現', body: '修繕案結案後，系統把派工、到場、施工、驗收變成一段匠城出任務動畫，業主點開就看得懂這次修了什麼。' },
    { title: 'Washgo 洗滌追蹤：匠城呈現', body: '客人查送洗進度時，收件、洗護、品管、送回會以匠城動畫一路播完，等衣服的時間也有東西看。' },
  ],
  homePages: [
    { title: 'Go 幫你發文', body: '工班不用自己顧粉專。每週兩則，一個月 999。', cta: '看價格表' },
    { title: '三品牌發文與報導', body: '三個品牌的累計發文、曝光與互動，加上最新貼文和經濟日報。', cta: '看成果' },
    { title: '三小編熱聊', body: '同一套中心做出的 Podcast，SoundOn、YouTube、Spotify 都能聽。', cta: '去收聽' },
    { title: '匠城出任務', body: '收工後跑一班。遊戲也接進 TaskGo 結案報告和 Washgo 洗滌追蹤。', cta: '玩一局' },
    { title: '行銷中心怎麼跑', body: '題材、生成、審閱、發布、學習。工班看到的貼文都從這裡出來。', cta: '看流程' },
  ],
  home: {
    title: '匠管的 AI 行銷中心',
    eyebrow: 'GO Marketing Center',
    h1a: '匠管為三個品牌',
    h1b: '打造的 AI 行銷中心',
    lead1: '匠管同時經營 TaskGo、Homigo、Washgo，人手不可能每天顧三組粉專。所以我們做了 GO 行銷中心：它會自己在 Facebook、Instagram、Threads 發文，三位小編阿豪、小咪、阿樂各有固定人設與口吻，還能自己錄 Podcast。',
    lead2: '我們也做了小遊戲「匠城出任務」讓師傅收工後舒壓，並把它接進 TaskGo 與 Washgo 系統裡。',
    ctaGame: '直接玩匠城出任務',
    ctaPrice: '每週兩篇，一個月 999',
    gameEyebrow: '先玩一局',
    gameTitle: '匠城出任務',
    gameSub: '騎車接 TaskGo 報修、Homigo 送鑰匙、Washgo 收衣服。90 秒就能開跑，不用註冊。想全螢幕玩，直接開遊戲頁。',
    openGame: '開啟完整遊戲',
    gameMore: '地圖、排行榜與系統裡的匠城呈現',
    postsEyebrow: '品牌發文',
    postsTitle: '三位 AI 小編，各自顧一個品牌',
    postsSub: '每個品牌只放最新發出去的一則，內容由小編依品牌口吻產出、團隊審過才上線。',
    priceEyebrow: '給工班的方案',
    priceTitle: 'Go 幫你發文，只收 999／月',
    priceSub: '同一套會自己發文的中心，現在可以幫工班、店家每週寫兩則。不是另外一套系統的月費。',
    priceMeta: '每週 2 則 · Facebook、Instagram、Threads',
    priceUnit: ' 元／月',
    priceNote: 'AI 小編撰寫，發布前有人看過才上線。沒有第二種方案。',
    priceCta: '看完整價格表',
    priceAside: '這套中心先拿來經營匠管自己的三個品牌。工班可以先看成果，再決定要不要讓 Go 幫你發。',
    priceProof: '看三品牌發文成果',
    pagesEyebrow: '分頁看',
    pagesTitle: '每一塊都可以單獨看完',
  },
  results: {
    fail: '成效數字暫時載入不到。下面仍可看最新貼文與報導。',
    loading: '成效載入中…',
    published: '累計已發',
    publishedHint: '三個平台合計',
    impressions: '累計曝光',
    since: (month: string | null) => (month ? `${month}起，被看到的次數` : '已發出貼文被看到的次數'),
    last28Impressions: '近 28 天曝光',
    last28Posts: (n: string) => `近 28 天發出 ${n} 則`,
    last28Interactions: '近 28 天互動',
    interactionDetail: (likes: string, comments: string, shares: string, saves: string) => `按讚 ${likes}、留言 ${comments}、分享 ${shares}、收藏 ${saves}`,
    byBrand: '三個品牌各自的成果',
    allPublished: '累計已發',
    recentPublished: '近 28 天已發',
    allImpressions: '累計曝光',
    recentImpressions: '近 28 天曝光',
    recentInteractions: '近 28 天互動',
    mix: (likes: string, comments: string, shares: string, saves: string, clicks: string | null) => {
      const base = `按讚 ${likes} · 留言 ${comments} · 分享 ${shares} · 收藏 ${saves}`;
      return clicks ? `${base} · 連結點擊 ${clicks}` : base;
    },
    byPlatform: '三個平台各自貢獻多少',
    platformPending: '曝光還在向平台回收',
    platformCounts: (all: string, recent: string) => `累計曝光 ${all} · 近 28 天 ${recent}`,
    platformRecent: (published: string, interactions: string) => `近 28 天已發 ${published} 則 · 互動 ${interactions}`,
    footnote: (refreshedAt: string | null, threadsMain: boolean, clicks: string | null) => {
      let text = `已發篇數約每兩分鐘更新。曝光與互動約每小時向各平台回收${refreshedAt ? `，最近一次回收是 ${refreshedAt}` : ''}。數字來自各平台官方成效，不含廣告。一則內容發到幾個平台，就各算一則。`;
      if (threadsMain) text += '目前看得到的曝光，主要來自 Threads。';
      if (clicks) text += `另有累計連結點擊 ${clicks}。`;
      return text;
    },
  },
  trend: {
    aria: '近八週曝光走勢',
    title: '三個品牌在台灣的曝光走勢',
    sub: '近八週發出的貼文，到目前被看到的次數。受眾在台灣，這張圖看的是發文成效。',
    total: '近八週曝光',
    chartAria: '近八週三品牌曝光折線',
    tooltip: (week: string, n: string) => `${week} 被看到 ${n} 次`,
    detail: (week: string, posts: string, views: string, interactions: string) => `${week} 那週發出 ${posts} 則，到目前被看到 ${views} 次，互動 ${interactions} 次。`,
    split: (interactions: string) => `曝光 · 互動 ${interactions}`,
    reach: '近 28 天，誰被看到比較多',
    weeksAria: '選擇週次',
  },
  map: { s: '小地圖', m: '中地圖', l: '大地圖', t: '台灣地圖' },
  board: {
    eyebrow: (map: string) => `排行榜・${map}`,
    fallbackTitle: '全站排行',
    season: (start: string, end: string, map: string, topN: number) => `活動期間 ${start} – ${end}，${map}前 ${topN} 名可獲獎`,
    onShiftNow: '正在上工',
    totalPlays: '累計遊玩（局）',
    totalMinutes: '累計上工（分鐘）',
    playerCount: '玩家人數',
    tabs: { rank: '排行榜', live: '正在玩', loyal: '最常上工' },
    rankFail: '排行榜暫時載入失敗，請稍後再試。',
    emptyRank: '還沒有人上榜，第一名等你來拿。',
    emptyLive: '現在沒有人在跑單。',
    emptyLoyal: '還沒有常客。玩完送出成績後會出現在這裡。',
    onShift: (stay: string) => `已上工 ${stay}`,
    loyalMeta: (phone: string, minutes: number) => `${phone}・${minutes} 分鐘`,
    rounds: (plays: number) => `${plays} 局`,
    rules: '活動辦法與領獎方式',
    prizeOriginal: '',
    stay: (seconds: number) => (seconds < 60 ? `${seconds} 秒` : `${Math.floor(seconds / 60)} 分 ${seconds % 60} 秒`),
  },
  gameFrame: {
    title: '匠城出任務',
    alt: '匠城出任務遊戲畫面',
    play: '開始遊戲',
    fullscreen: '全螢幕開啟',
    hint: '手機直接點「全螢幕開啟」操作最順',
  },
  posting: {
    title: 'Go 幫你發文',
    eyebrow: '給工班與店家',
    h1a: 'Go 幫你發文',
    h1b: '只收你 999／月',
    lead: '匠管用這套中心幫 TaskGo、Homigo、Washgo 發文。現在同一套做法開放給工班和店家：你不用自己想題目、寫文案、記得按發布。每週兩則，一個月 999 元。',
    cta: '填需求，我們聯絡你',
    proof: '先看三品牌怎麼發',
    only: '只有這一檔',
    unit: ' 元／月',
    heroNote: '每週 2 則，發到 Facebook、Instagram、Threads。',
    posterAlt: 'GO 行銷中心 DM：讓 AI 幫你找資料、想內容、做文案、排程發文。流程是搜尋資料、AI 分析、產生文案、人工審核、排程發布。正在招募測試夥伴。',
    posterCaption: '',
    tableEyebrow: '價格表',
    tableTitle: '一個方案，看這張表就好',
    plan: [
      ['方案', 'Go 幫你發文'],
      ['每週篇數', '2 則'],
      ['發到哪', 'Facebook、Instagram、Threads'],
      ['誰來寫', 'AI 小編依你的行業口吻寫'],
      ['發布前', '有人看過才上線'],
      ['月費', 'NT$ 999'],
    ] as [string, string][],
    tableNote: '價格含撰寫與發布。沒有年約方案、沒有加價方案。',
    includedTitle: '999 元裡面有什麼',
    includedHead: ['包含', '說明'] as [string, string],
    included: [
      ['每週兩則貼文', '一個月約八則，不是每天一則'],
      ['三個平台', '同一則可以發到 Facebook、Instagram、Threads'],
      ['小編撰寫', '用行銷中心的 AI 小編寫，不是空白範本讓你自己填'],
      ['人工審過', '發出之前會先看過'],
    ] as [string, string][],
    excludedTitle: '這筆錢不包含',
    excludedHead: ['不包含', '說明'] as [string, string],
    excluded: [
      ['廣告投放', '不含買廣告、不含保證曝光'],
      ['拍片與 Podcast', '不含幫你錄 Podcast 或拍短片'],
      ['官網長文', '不含官網 SEO 文章'],
      ['系統月費', '這不是 TaskGo、Homigo、Washgo 的軟體月費'],
    ] as [string, string][],
    startEyebrow: '怎麼開始',
    startTitle: '留下聯絡方式，我們會打給你',
    steps: [
      { title: '填表', body: '姓名、手機、行業。想先講的話也可以寫在備註。' },
      { title: '對口吻', body: '我們用行銷中心的小編，依你的行業寫，不是套三個品牌的現成文。' },
      { title: '每週兩則', body: '寫好、審過，發到你的 Facebook、Instagram 或 Threads。' },
      { title: '一個月 999', body: '下個月同一件事再做。不想續就跟我們說一聲。' },
    ],
    contactNote: (email: string) => `開通與續約由匠管團隊處理，這個網站沒有線上刷卡。也可以改寄信到 ${email}。`,
  },
  inquiry: {
    website: '網站',
    name: '姓名',
    phone: '手機',
    phonePlaceholder: '09xxxxxxxx',
    line: 'LINE ID（選填）',
    linePlaceholder: '沒有可以空白',
    trade: '行業或店名',
    tradePlaceholder: '例如：水電工班、洗衣店',
    message: '想先跟我們說的話（選填）',
    messagePlaceholder: '服務範圍、不能講的話、想先問的問題',
    duplicate: '這支手機今天已經留過資料，我們會再跟你聯絡。',
    ok: '已收到。我們會用這支手機跟你聯絡。',
    fail: '送出失敗，請再試一次',
    sending: '送出中…',
    submit: '送出，請跟我聯絡',
  },
  proof: {
    title: '三品牌發文與媒體曝光',
    eyebrow: '品牌成果',
    h1: '三個品牌發了多少、帶來多少',
    lead: '阿豪顧 TaskGo、小咪顧 Homigo、阿樂顧 Washgo，都在 Facebook、Instagram、Threads 發文。下面先看三個品牌加總的成果，再看各品牌最新一則，以及經濟日報的報導。',
    resultsEyebrow: '發文成效',
    resultsTitle: '整體成果，一眼看完',
    resultsSub: '有興趣的客戶可以直接看近八週的曝光走勢，以及三個品牌的發文量、曝光與互動。已發篇數大約每兩分鐘更新；曝光與互動約每小時向平台回收，平台數字本身還會再晚幾個小時才補齊。',
    postsEyebrow: '最新貼文',
    postsTitle: '每個品牌最近發出的一則',
    postsSub: '人設固定，口吻不混。點進去可以看原文。',
    pressEyebrow: '媒體曝光',
    pressTitle: '經濟日報報導過的三個品牌',
    pressSub: '標題與日期來自報導本身。內文請點原文，我們不轉載全文。',
    read: '閱讀原文',
    brandsEyebrow: '三個品牌',
    brandsTitle: '修繕、租屋、洗衣，各有一個小編',
    fixedEditor: (name: string) => `固定小編：${name}`,
    cta: '想要一樣的發文，看 999 方案',
  },
  show: {
    title: '三小編熱聊',
    eyebrow: 'Podcast',
    h1: '行銷中心也會做節目',
    lead: '《GO三小編熱聊》由同一套中心產出：題目、腳本、三位小編的聲音，再到 SoundOn 上架。工班、房東、洗衣店聽的是生活裡用得到的事，不是產品發表會。',
    hostsTitle: '三位主持人，人設跟貼文是同一組',
    hosts: {
      taskgo: '工班出身。聊報價、派工、業主現場那些不能只靠嘴巴交代的事。',
      homigo: '包租管家。聊租約、修繕責任、房東房客怎麼把話說清楚。',
      washgo: '洗衣店店員。聊衣物、收送、客人臨時改需求時店裡怎麼接。',
    },
    note: '節目頁只放最新一集。完整集數在 SoundOn。訂閱連結不會顯示聯絡信箱。',
    cta: '看這套中心還能做什麼',
  },
  center: {
    title: '行銷中心怎麼運作',
    eyebrow: '怎麼運作',
    h1: '貼文不是臨時想到才寫',
    lead: 'GO 行銷中心是匠管為了同時經營三個品牌做出來的。題材進來、小編生成、人審過、發出去、成效再流回來。工班在粉專上看到的那一則，走的就是這個循環。',
    flowTitle: '從題材到成效',
    modulesEyebrow: '功能模組',
    modulesTitle: '行銷團隊每天開的是這些',
    modulesSub: '這些是中心內部的工作台，不是 999 方案會另外開給你的後台。Go 幫你發文用的是同一套撰寫和發布，你收到的是每週兩則已審過的貼文。',
    cta: '看 999 方案包含什麼',
    show: '聽三小編熱聊',
  },
  game: {
    title: '匠城出任務',
    eyebrow: '遊戲挑戰',
    h1: '收工以後，跑一班舒壓',
    lead: '匠城出任務是給工班互動的小遊戲：騎車接 TaskGo 報修、Homigo 送鑰匙、Washgo 收衣服。介面現在有 English、日本語、Tiếng Việt、Bahasa Indonesia。先讓人用自己的語言，體驗在台灣跑一班的天氣、垃圾車和路上突發。玩完可以上排行榜，同一套呈現也接進 TaskGo 和 Washgo 的系統裡。',
    posterAlt: '匠城出任務四種語言畫面：English 的 Craft City Rush、日本語的匠シティ・ラッシュ、Tiếng Việt 與 Bahasa Indonesia。同一條台灣街道，慢字路標分別是 SLOW、徐行、CHẬM、PELAN。',
    posterCaption: '同一條台灣街。English、日本語、Tiếng Việt、Bahasa Indonesia 都能上手，先體驗在台灣跑一班。',
    mapTitle: '地圖怎麼解',
    steps: [
      { title: '小地圖', body: '90 秒，先熟悉接單、打卡、回程。' },
      { title: '中地圖、大地圖', body: '單變多，天氣和路上狀況每班不一樣。' },
      { title: '台灣地圖', body: '邀請朋友才開得了的隱藏版。' },
      { title: '排行榜', body: '暱稱上場，電話只顯示遮罩。連單營收越高，越有機會拿獎。' },
    ],
    embedTitle: '已經接進系統的匠城呈現',
    embedSub: '結案或查進度時，流程直接在下面播成一段匠城動畫。客戶不用再按開啟，就能看到派工、施工、洗滌這些資訊怎麼串在一起。',
    demoNote: '測試場域展示，並非真實客戶或真實案件。',
    openFull: '另開完整畫面',
    cta: '看 Go 幫你發文',
  },
  week: {
    eyebrow: '本月',
    title: '這個月的累計還在往上加',
    sub: '數字來自實際開局，以台北時間換月。柱子是本月一天一天加總，所以只會越長越高。單日有人多有人少，看的是這個月整體。',
    fail: '這個月的數字暫時讀不到。',
    fallbackLabel: '本月累計還在往上加',
    todayAdded: (n: string) => ` 今天又加了 ${n} 局。`,
    plays: '本月累計開局',
    done: '本月跑完',
    players: '本月不重複玩家',
    stayLabel: '本月累計停留',
    previousFallback: '上個月',
    previousMonthRuns: (name: string) => `${name}整月開局`,
    jobs: '本月遊戲裡完成的單',
    barsAria: '本月累計開局',
    today: '今天',
    cumulativeNote: '柱上的數字是加到當天的累計，不是當天單日。',
    jobTaskgo: (n: string) => `TaskGo 報修 ${n}`,
    jobHomigo: (n: string) => `Homigo 送鑰匙 ${n}`,
    jobWashgo: (n: string) => `Washgo 收送 ${n}`,
    stay: (minutes: number) => {
      if (minutes < 60) return `${minutes} 分`;
      const hours = minutes / 60;
      return `${hours >= 10 ? Math.round(hours).toLocaleString('en-US') : hours.toFixed(1)} 小時`;
    },
    story: (input: {
      level: 'steady' | 'building';
      month: number;
      dayCount: number;
      current: string;
      previous: string;
      previousPlays: number;
      today: string;
    }) => {
      const name = `${input.month}月`;
      const prev = input.month === 1 ? 12 : input.month - 1;
      const previousLabel = `${prev}月`;
      if (input.previousPlays <= 0) {
        return {
          label: '本月累計還在往上加',
          detail: `${name}過了 ${input.dayCount} 天，累計 ${input.current} 局。柱子是加總，只會一天比一天高。今天又加了 ${input.today} 局。`,
          previousLabel,
        };
      }
      if (input.level === 'steady') {
        return {
          label: '這個月已經超過上個月',
          detail: `${name}才過 ${input.dayCount} 天，累計 ${input.current} 局，已經多過${previousLabel}整月的 ${input.previous} 局。今天又加了 ${input.today} 局。`,
          previousLabel,
        };
      }
      return {
        label: '本月累計還在往上加',
        detail: `${name}過了 ${input.dayCount} 天，累計 ${input.current} 局。${previousLabel}整月是 ${input.previous} 局。單日有高有低，這張圖看的是加總。今天又加了 ${input.today} 局。`,
        previousLabel,
      };
    },
  },
  scenes: {
    eyebrow: '這一班會遇到',
    title: '任務和路上的突發，每一局都不一樣',
    sub: '90 秒裡要接三種單，路上還會隨機冒出台灣日常。下面是玩家收工時會截到的畫面，進遊戲才撞得到下一張。',
    incidentsAlt: '匠城出任務的隨機突發：野狗追車、警察臨檢、垃圾車、油箱見底、手搖飲。',
    incidentsCaption: '野狗、臨檢、垃圾車、加油、手搖。這些是每一班都可能遇上的日常。',
    momentsAlt: '匠城出名場面截圖：土狗包圍、高雄下雪還在送洗衣、垃圾車一響全巷子在跑，以及車庫裡的四台機車。',
    momentsCaption: '收工會自動截一張名場面。土狗、送洗、垃圾車，還能換成自己的車。',
    doneLabel: '這個月玩家完成',
    times: (n: string) => `${n} 次`,
    more: '還有消防車、吊車、公車拋錨、街頭拍 MV、臨時市集、道路積水、倒樹。共 21 種隨機路況，玩一局才知道今天撞見哪一種。',
    cta: '進遊戲跑一班',
    tasks: [
      { title: '報修派工', body: '騎到現場停一下，GPS 打卡、施工、拍照上傳。' },
      { title: '送鑰匙交屋', body: '把鑰匙送到新房客手上，燈一亮，這戶就算入住。' },
      { title: '衣物收送', body: '沿路收衣服、送去洗，再送回客人手上。' },
    ],
    items: [
      { title: '野狗追車', line: '被土狗包圍，師傅當場投降' },
      { title: '警察臨檢', line: '停車受檢有獎金，闖過去就罰單' },
      { title: '垃圾車來了', line: '給愛麗絲一響，全巷子都在跑' },
      { title: '手搖飲', line: '喝一杯，全速衝刺幾秒' },
      { title: '雞群過馬路', line: '一群雞霸佔馬路，全部的車都在等' },
      { title: '貓咪卡在車底', line: '全城最重要的任務：把貓救出來' },
      { title: '選舉造勢', line: '車隊佔住整條路，師傅被塞了一份傳單' },
      { title: '廟會遶境', line: '鞭炮陣頭經過，順便求個收工平安' },
      { title: '婚禮車隊', line: '跟在後面，有機會拿到喜糖' },
      { title: '外送大軍', line: '商圈尖峰，師傅被擠成夾心' },
      { title: '突然暴雨', line: '出門還是大太陽，騎到一半天空變黑' },
      { title: '巨大坑洞', line: '全速撞進去，工具箱差點飛出去' },
      { title: '前方施工', line: '導航說直走，結果直接撞上圍籬' },
      { title: '救護車', line: '讓道有獎金，擋住就扣分' },
      { title: '學校放學', line: '學生和家長擠滿路口，騎慢一點' },
    ],
  },
  wishes: {
    eyebrow: '留言板',
    title: '想要什麼新功能，留在這裡',
    sub: '玩完一局有想法，直接寫下來。可以是新地圖、新任務，或路上還想遇到的突發。暱稱可以不填。',
    kindGroup: '留言類型',
    kinds: { feature: '想要的功能', bug: '遇到的問題', cheer: '給師傅的話' },
    nickname: '暱稱',
    nicknamePlaceholder: '可不填，最多 12 字',
    body: '想說的話',
    bodyPlaceholder: '例如：台灣地圖想多幾個夜市，垃圾車可以再快一點',
    company: '公司',
    sending: '送出中…',
    submit: '貼上留言板',
    ok: '收到了。其他玩家也看得到，也可以按「我也想要」。',
    fail: '送出失敗，請稍後再試',
    cannotSupport: '這個暫時按不了',
    newest: '最新',
    hottest: '最多人想要',
    empty: '第一則想要的功能，等你來留。',
    support: (n: number) => `我也想要 ${n}`,
  },
};

export type PublicCopy = typeof zh;
